/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.47
 * Generated at: 2022-02-02 06:17:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class faq_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/E:/HelperLand/helperland/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/helperland/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1626333475988L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  \r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("   <link rel=\"stylesheet\" href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("  <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\"\r\n");
      out.write("    integrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("  <title>FAQ</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("  <div class=\"container-fluid main position-relative p-0\">\r\n");
      out.write("    <nav class=\"navbar navbar-expand-xl\" id=\"navbar\">\r\n");
      out.write("      <div class=\"container-fluid navbar_main\">\r\n");
      out.write("        <a class=\"navbar-brand py-0\" href=\"homepage.html\">\r\n");
      out.write("          <img src=\"images/logo-small.png\" alt=\"\" height=\"54px\" width=\"73px\" >\r\n");
      out.write("        </a>\r\n");
      out.write("        <button class=\"navbar-toggler text-white\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarText\"\r\n");
      out.write("          aria-controls=\"navbarText\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("          <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"40\" height=\"40\" fill=\"#fff\" class=\"bi bi-list\"\r\n");
      out.write("            viewBox=\"0 0 16 16\">\r\n");
      out.write("            <path fill-rule=\"evenodd\"\r\n");
      out.write("              d=\"M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z\" />\r\n");
      out.write("          </svg>\r\n");
      out.write("        </button>\r\n");
      out.write("        <div class=\"collapse navbar-collapse navbar_list\" id=\"navbarText\">\r\n");
      out.write("          <div class=\"nav-item navbar_book rounded-pill\">\r\n");
      out.write("            <a class=\"p-0 nav-link text-light\" href=\"#\">Book now</a>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"nav-item navbar_prices rounded-pill\">\r\n");
      out.write("            <a class=\"p-0 nav-link text-light\" href=\"prices.html\">Prices & services</a>\r\n");
      out.write("          </div>\r\n");
      out.write("          <ul class=\"navbar-nav me-auto mb-2 mb-lg-0 align-items-center justify-content-between\">\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link text-light\" href=\"#\">Warranty</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link text-light\" href=\"#\">Blog</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item navbar_contact\">\r\n");
      out.write("              <a class=\"nav-link text-light\" href=\"contactus.html\">Contact</a>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("          <div class=\"nav-item navbar_login rounded-pill\">\r\n");
      out.write("            <a href=\"#\" class=\"p-0 text-decoration-none text-light\">Login</a>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"nav-item navbar_helper rounded-pill\">\r\n");
      out.write("            <a href=\"#\" class=\"p-0 text-decoration-none text-light\">Become a Helper</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("    <div class=\"main_image\">\r\n");
      out.write("      <img src=\"images/group-18.png\" alt=\"\" height=\"370px\" width=\"auto\">\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("  <div class=\"container-fluid faqs\">\r\n");
      out.write("    <div class=\"faqs_heading position-relative\">\r\n");
      out.write("      <h1>FAQs</h1>\r\n");
      out.write("      <div class=\"faq_box\">\r\n");
      out.write("        <div class=\"left_line\"></div>\r\n");
      out.write("        <img src=\"images/separator.png\" alt=\"\">\r\n");
      out.write("        <div class=\"right_line\"></div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"faqs_content d-flex flex-column align-items-center justify-content-center position-relative\">\r\n");
      out.write("      <p class=\"content_head\">Whether you are Customer or Service provider,<br> We have tried our best to solve all\r\n");
      out.write("        your queries and questions.</p>\r\n");
      out.write("      <div class=\"faqs_accordion\">\r\n");
      out.write("        <div class=\"accordion_head d-flex align-items-center justify-content-between\">\r\n");
      out.write("          <div class=\"btn-1 d-flex align-items-center justify-content-center\" id=\"forCustomer\">FOR CUSTOMERS</div>\r\n");
      out.write("          <div class=\"btn-2 d-flex align-items-center justify-content-center\" id=\"forServiceProvider\">FOR SERVICE\r\n");
      out.write("            PROVIDER</div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"accordion position-relative w-100\" id=\"accordionCustomer\">\r\n");
      out.write("      <div class=\"accordion-item border-0\">\r\n");
      out.write("        <div class=\"accordion-header d-flex align-items-center\" id=\"headingOne\">\r\n");
      out.write("          <button class=\" btn collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#collapseOne\"\r\n");
      out.write("            aria-expanded=\"false\" aria-controls=\"collapseOne\">\r\n");
      out.write("            <img src=\"images/right-arrow.png\" alt=\"\" height=\"22\" width=\"22\">\r\n");
      out.write("          </button>\r\n");
      out.write("          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nisl nunc, iaculis mattis tellus ac\r\n");
      out.write("            ut non imperdiet velit?</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"collapseOne\" class=\"accordion-collapse collapse\" aria-labelledby=\"headingOne\"\r\n");
      out.write("          data-bs-parent=\"#accordionCustomer\">\r\n");
      out.write("          <div class=\"accordion-body\">\r\n");
      out.write("            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed id diam tincidunt, fringilla ante vitae,\r\n");
      out.write("            dapibus velit. Vivamus id tortor rhoncus, efficitur quam at, suscipit tortor. Integer fermentum convallis\r\n");
      out.write("            eros vel semper. Ut non imperdiet velit. Praesent eu dui vel lacus porta eleifend eget quis dui. Integer\r\n");
      out.write("            tempus massa in gravida tincidunt. Fusce in libero tristique, euismod nisi vel, luctus urna. Interdum et\r\n");
      out.write("            malesuada fames ac ante ipsum primis in faucibus. Donec et placerat arcu. Suspendisse lacinia tristique\r\n");
      out.write("            massa. Etiam risus justo, scelerisque id arcu eu, sodales tempor eros. Aliquam efficitur pretium urna, sit\r\n");
      out.write("            amet congue risus malesuada rutrum. Donec id massa vel velit ullamcorper accumsan ut eget nisl. Fusce\r\n");
      out.write("            viverra commodo lacus, sit amet facilisis leo luctus dictum.\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"accordion-item border-0\">\r\n");
      out.write("        <div class=\"accordion-header d-flex align-items-center\" id=\"headingTwo\">\r\n");
      out.write("          <button class=\" btn collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#collapseTwo\"\r\n");
      out.write("            aria-expanded=\"false\" aria-controls=\"collapseOne\">\r\n");
      out.write("            <img src=\"images/right-arrow.png\" alt=\"\" height=\"22\" width=\"22\">\r\n");
      out.write("          </button>\r\n");
      out.write("          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nisl nunc, iaculis mattis tellus ac\r\n");
      out.write("            ut non imperdiet velit?</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"collapseTwo\" class=\"accordion-collapse collapse\" aria-labelledby=\"headingTwo\"\r\n");
      out.write("          data-bs-parent=\"#accordionCustomer\">\r\n");
      out.write("          <div class=\"accordion-body\">\r\n");
      out.write("            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed id diam tincidunt, fringilla ante vitae,\r\n");
      out.write("            dapibus velit. Vivamus id tortor rhoncus, efficitur quam at, suscipit tortor. Integer fermentum convallis\r\n");
      out.write("            eros vel semper. Ut non imperdiet velit. Praesent eu dui vel lacus porta eleifend eget quis dui. Integer\r\n");
      out.write("            tempus massa in gravida tincidunt. Fusce in libero tristique, euismod nisi vel, luctus urna. Interdum et\r\n");
      out.write("            malesuada fames ac ante ipsum primis in faucibus. Donec et placerat arcu. Suspendisse lacinia tristique\r\n");
      out.write("            massa. Etiam risus justo, scelerisque id arcu eu, sodales tempor eros. Aliquam efficitur pretium urna, sit\r\n");
      out.write("            amet congue risus malesuada rutrum. Donec id massa vel velit ullamcorper accumsan ut eget nisl. Fusce\r\n");
      out.write("            viverra commodo lacus, sit amet facilisis leo luctus dictum.\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"accordion-item border-0\">\r\n");
      out.write("        <div class=\"accordion-header d-flex align-items-center\" id=\"headingThree\">\r\n");
      out.write("          <button class=\" btn collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#collapseThree\"\r\n");
      out.write("            aria-expanded=\"false\" aria-controls=\"collapseThree\">\r\n");
      out.write("            <img src=\"images/right-arrow.png\" alt=\"\" height=\"22\" width=\"22\">\r\n");
      out.write("          </button>\r\n");
      out.write("          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nisl nunc, iaculis mattis tellus ac\r\n");
      out.write("            ut non imperdiet velit?</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"collapseThree\" class=\"accordion-collapse collapse\" aria-labelledby=\"headingThree\"\r\n");
      out.write("          data-bs-parent=\"#accordionCustomer\">\r\n");
      out.write("          <div class=\"accordion-body\">\r\n");
      out.write("            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed id diam tincidunt, fringilla ante vitae,\r\n");
      out.write("            dapibus velit. Vivamus id tortor rhoncus, efficitur quam at, suscipit tortor. Integer fermentum convallis\r\n");
      out.write("            eros vel semper. Ut non imperdiet velit. Praesent eu dui vel lacus porta eleifend eget quis dui. Integer\r\n");
      out.write("            tempus massa in gravida tincidunt. Fusce in libero tristique, euismod nisi vel, luctus urna. Interdum et\r\n");
      out.write("            malesuada fames ac ante ipsum primis in faucibus. Donec et placerat arcu. Suspendisse lacinia tristique\r\n");
      out.write("            massa. Etiam risus justo, scelerisque id arcu eu, sodales tempor eros. Aliquam efficitur pretium urna, sit\r\n");
      out.write("            amet congue risus malesuada rutrum. Donec id massa vel velit ullamcorper accumsan ut eget nisl. Fusce\r\n");
      out.write("            viverra commodo lacus, sit amet facilisis leo luctus dictum.\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"accordion-item border-0\">\r\n");
      out.write("        <div class=\"accordion-header d-flex align-items-center\" id=\"headingFour\">\r\n");
      out.write("          <button class=\" btn collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#collapseFour\"\r\n");
      out.write("            aria-expanded=\"false\" aria-controls=\"collapseThree\">\r\n");
      out.write("            <img src=\"images/right-arrow.png\" alt=\"\" height=\"22\" width=\"22\">\r\n");
      out.write("          </button>\r\n");
      out.write("          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nisl nunc, iaculis mattis tellus ac\r\n");
      out.write("            ut non imperdiet velit?</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"collapseFour\" class=\"accordion-collapse collapse\" aria-labelledby=\"headingFour\"\r\n");
      out.write("          data-bs-parent=\"#accordionCustomer\">\r\n");
      out.write("          <div class=\"accordion-body\">\r\n");
      out.write("            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed id diam tincidunt, fringilla ante vitae,\r\n");
      out.write("            dapibus velit. Vivamus id tortor rhoncus, efficitur quam at, suscipit tortor. Integer fermentum convallis\r\n");
      out.write("            eros vel semper. Ut non imperdiet velit. Praesent eu dui vel lacus porta eleifend eget quis dui. Integer\r\n");
      out.write("            tempus massa in gravida tincidunt. Fusce in libero tristique, euismod nisi vel, luctus urna. Interdum et\r\n");
      out.write("            malesuada fames ac ante ipsum primis in faucibus. Donec et placerat arcu. Suspendisse lacinia tristique\r\n");
      out.write("            massa. Etiam risus justo, scelerisque id arcu eu, sodales tempor eros. Aliquam efficitur pretium urna, sit\r\n");
      out.write("            amet congue risus malesuada rutrum. Donec id massa vel velit ullamcorper accumsan ut eget nisl. Fusce\r\n");
      out.write("            viverra commodo lacus, sit amet facilisis leo luctus dictum.\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"accordion-item border-0\">\r\n");
      out.write("        <div class=\"accordion-header d-flex align-items-center\" id=\"headingFive\">\r\n");
      out.write("          <button class=\" btn collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#collapseFive\"\r\n");
      out.write("            aria-expanded=\"false\" aria-controls=\"collapseThree\">\r\n");
      out.write("            <img src=\"images/right-arrow.png\" alt=\"\" height=\"22\" width=\"22\">\r\n");
      out.write("          </button>\r\n");
      out.write("          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nisl nunc, iaculis mattis tellus ac\r\n");
      out.write("            ut non imperdiet velit?</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"collapseFive\" class=\"accordion-collapse collapse\" aria-labelledby=\"headingFive\"\r\n");
      out.write("          data-bs-parent=\"#accordionCustomer\">\r\n");
      out.write("          <div class=\"accordion-body\">\r\n");
      out.write("            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed id diam tincidunt, fringilla ante vitae,\r\n");
      out.write("            dapibus velit. Vivamus id tortor rhoncus, efficitur quam at, suscipit tortor. Integer fermentum convallis\r\n");
      out.write("            eros vel semper. Ut non imperdiet velit. Praesent eu dui vel lacus porta eleifend eget quis dui. Integer\r\n");
      out.write("            tempus massa in gravida tincidunt. Fusce in libero tristique, euismod nisi vel, luctus urna. Interdum et\r\n");
      out.write("            malesuada fames ac ante ipsum primis in faucibus. Donec et placerat arcu. Suspendisse lacinia tristique\r\n");
      out.write("            massa. Etiam risus justo, scelerisque id arcu eu, sodales tempor eros. Aliquam efficitur pretium urna, sit\r\n");
      out.write("            amet congue risus malesuada rutrum. Donec id massa vel velit ullamcorper accumsan ut eget nisl. Fusce\r\n");
      out.write("            viverra commodo lacus, sit amet facilisis leo luctus dictum.\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"accordion-item border-0\">\r\n");
      out.write("        <div class=\"accordion-header d-flex align-items-center\" id=\"headingSix\">\r\n");
      out.write("          <button class=\" btn collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#collapseSix\"\r\n");
      out.write("            aria-expanded=\"false\" aria-controls=\"collapseThree\">\r\n");
      out.write("            <img src=\"images/right-arrow.png\" alt=\"\" height=\"22\" width=\"22\">\r\n");
      out.write("          </button>\r\n");
      out.write("          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nisl nunc, iaculis mattis tellus ac\r\n");
      out.write("            ut non imperdiet velit?</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"collapseSix\" class=\"accordion-collapse collapse\" aria-labelledby=\"headingSix\"\r\n");
      out.write("          data-bs-parent=\"#accordionCustomer\">\r\n");
      out.write("          <div class=\"accordion-body\">\r\n");
      out.write("            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed id diam tincidunt, fringilla ante vitae,\r\n");
      out.write("            dapibus velit. Vivamus id tortor rhoncus, efficitur quam at, suscipit tortor. Integer fermentum convallis\r\n");
      out.write("            eros vel semper. Ut non imperdiet velit. Praesent eu dui vel lacus porta eleifend eget quis dui. Integer\r\n");
      out.write("            tempus massa in gravida tincidunt. Fusce in libero tristique, euismod nisi vel, luctus urna. Interdum et\r\n");
      out.write("            malesuada fames ac ante ipsum primis in faucibus. Donec et placerat arcu. Suspendisse lacinia tristique\r\n");
      out.write("            massa. Etiam risus justo, scelerisque id arcu eu, sodales tempor eros. Aliquam efficitur pretium urna, sit\r\n");
      out.write("            amet congue risus malesuada rutrum. Donec id massa vel velit ullamcorper accumsan ut eget nisl. Fusce\r\n");
      out.write("            viverra commodo lacus, sit amet facilisis leo luctus dictum.\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"accordion-item border-0\">\r\n");
      out.write("        <div class=\"accordion-header d-flex align-items-center\" id=\"headingSeven\">\r\n");
      out.write("          <button class=\" btn collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#collapseSeven\"\r\n");
      out.write("            aria-expanded=\"false\" aria-controls=\"collapseThree\">\r\n");
      out.write("            <img src=\"images/right-arrow.png\" alt=\"\" height=\"22\" width=\"22\">\r\n");
      out.write("          </button>\r\n");
      out.write("          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nisl nunc, iaculis mattis tellus ac\r\n");
      out.write("            ut non imperdiet velit?</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"collapseSeven\" class=\"accordion-collapse collapse\" aria-labelledby=\"headingSeven\"\r\n");
      out.write("          data-bs-parent=\"#accordionCustomer\">\r\n");
      out.write("          <div class=\"accordion-body\">\r\n");
      out.write("            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed id diam tincidunt, fringilla ante vitae,\r\n");
      out.write("            dapibus velit. Vivamus id tortor rhoncus, efficitur quam at, suscipit tortor. Integer fermentum convallis\r\n");
      out.write("            eros vel semper. Ut non imperdiet velit. Praesent eu dui vel lacus porta eleifend eget quis dui. Integer\r\n");
      out.write("            tempus massa in gravida tincidunt. Fusce in libero tristique, euismod nisi vel, luctus urna. Interdum et\r\n");
      out.write("            malesuada fames ac ante ipsum primis in faucibus. Donec et placerat arcu. Suspendisse lacinia tristique\r\n");
      out.write("            massa. Etiam risus justo, scelerisque id arcu eu, sodales tempor eros. Aliquam efficitur pretium urna, sit\r\n");
      out.write("            amet congue risus malesuada rutrum. Donec id massa vel velit ullamcorper accumsan ut eget nisl. Fusce\r\n");
      out.write("            viverra commodo lacus, sit amet facilisis leo luctus dictum.\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"accordion-item border-0\">\r\n");
      out.write("        <div class=\"accordion-header d-flex align-items-center\" id=\"headingEight\">\r\n");
      out.write("          <button class=\" btn collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#collapseEight\"\r\n");
      out.write("            aria-expanded=\"false\" aria-controls=\"collapseThree\">\r\n");
      out.write("            <img src=\"images/right-arrow.png\" alt=\"\" height=\"22\" width=\"22\">\r\n");
      out.write("          </button>\r\n");
      out.write("          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nisl nunc, iaculis mattis tellus ac\r\n");
      out.write("            ut non imperdiet velit?</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"collapseEight\" class=\"accordion-collapse collapse\" aria-labelledby=\"headingEight\"\r\n");
      out.write("          data-bs-parent=\"#accordionCustomer\">\r\n");
      out.write("          <div class=\"accordion-body\">\r\n");
      out.write("            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed id diam tincidunt, fringilla ante vitae,\r\n");
      out.write("            dapibus velit. Vivamus id tortor rhoncus, efficitur quam at, suscipit tortor. Integer fermentum convallis\r\n");
      out.write("            eros vel semper. Ut non imperdiet velit. Praesent eu dui vel lacus porta eleifend eget quis dui. Integer\r\n");
      out.write("            tempus massa in gravida tincidunt. Fusce in libero tristique, euismod nisi vel, luctus urna. Interdum et\r\n");
      out.write("            malesuada fames ac ante ipsum primis in faucibus. Donec et placerat arcu. Suspendisse lacinia tristique\r\n");
      out.write("            massa. Etiam risus justo, scelerisque id arcu eu, sodales tempor eros. Aliquam efficitur pretium urna, sit\r\n");
      out.write("            amet congue risus malesuada rutrum. Donec id massa vel velit ullamcorper accumsan ut eget nisl. Fusce\r\n");
      out.write("            viverra commodo lacus, sit amet facilisis leo luctus dictum.\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"accordion-item border-0\">\r\n");
      out.write("        <div class=\"accordion-header d-flex align-items-center\" id=\"headingNine\">\r\n");
      out.write("          <button class=\" btn collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#collapseNine\"\r\n");
      out.write("            aria-expanded=\"false\" aria-controls=\"collapseThree\">\r\n");
      out.write("            <img src=\"images/right-arrow.png\" alt=\"\" height=\"22\" width=\"22\">\r\n");
      out.write("          </button>\r\n");
      out.write("          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nisl nunc, iaculis mattis tellus ac\r\n");
      out.write("            ut non imperdiet velit?</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"collapseNine\" class=\"accordion-collapse collapse\" aria-labelledby=\"headingNine\"\r\n");
      out.write("          data-bs-parent=\"#accordionCustomer\">\r\n");
      out.write("          <div class=\"accordion-body\">\r\n");
      out.write("            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed id diam tincidunt, fringilla ante vitae,\r\n");
      out.write("            dapibus velit. Vivamus id tortor rhoncus, efficitur quam at, suscipit tortor. Integer fermentum convallis\r\n");
      out.write("            eros vel semper. Ut non imperdiet velit. Praesent eu dui vel lacus porta eleifend eget quis dui. Integer\r\n");
      out.write("            tempus massa in gravida tincidunt. Fusce in libero tristique, euismod nisi vel, luctus urna. Interdum et\r\n");
      out.write("            malesuada fames ac ante ipsum primis in faucibus. Donec et placerat arcu. Suspendisse lacinia tristique\r\n");
      out.write("            massa. Etiam risus justo, scelerisque id arcu eu, sodales tempor eros. Aliquam efficitur pretium urna, sit\r\n");
      out.write("            amet congue risus malesuada rutrum. Donec id massa vel velit ullamcorper accumsan ut eget nisl. Fusce\r\n");
      out.write("            viverra commodo lacus, sit amet facilisis leo luctus dictum.\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"accordion position-relative w-100\" id=\"accordionServiceProvider\">\r\n");
      out.write("      <div class=\"accordion-item border-0\">\r\n");
      out.write("        <div class=\"accordion-header d-flex align-items-center\" id=\"headingOne\">\r\n");
      out.write("          <button class=\" btn collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#collapseOne\"\r\n");
      out.write("            aria-expanded=\"false\" aria-controls=\"collapseOne\">\r\n");
      out.write("            <img src=\"images/down-arrow.png\" alt=\"\" height=\"22\" width=\"22\">\r\n");
      out.write("          </button>\r\n");
      out.write("          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nisl nunc, iaculis mattis tellus ac\r\n");
      out.write("            ut non imperdiet velit?</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"collapseOne\" class=\"accordion-collapse collapse\" aria-labelledby=\"headingOne\"\r\n");
      out.write("          data-bs-parent=\"#accordionServiceProvider\">\r\n");
      out.write("          <div class=\"accordion-body\">\r\n");
      out.write("            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed id diam tincidunt, fringilla ante vitae,\r\n");
      out.write("            dapibus velit. Vivamus id tortor rhoncus, efficitur quam at, suscipit tortor. Integer fermentum convallis\r\n");
      out.write("            eros vel semper. Ut non imperdiet velit. Praesent eu dui vel lacus porta eleifend eget quis dui. Integer\r\n");
      out.write("            tempus massa in gravida tincidunt. Fusce in libero tristique, euismod nisi vel, luctus urna. Interdum et\r\n");
      out.write("            malesuada fames ac ante ipsum primis in faucibus. Donec et placerat arcu. Suspendisse lacinia tristique\r\n");
      out.write("            massa. Etiam risus justo, scelerisque id arcu eu, sodales tempor eros. Aliquam efficitur pretium urna, sit\r\n");
      out.write("            amet congue risus malesuada rutrum. Donec id massa vel velit ullamcorper accumsan ut eget nisl. Fusce\r\n");
      out.write("            viverra commodo lacus, sit amet facilisis leo luctus dictum.\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"accordion-item border-0\">\r\n");
      out.write("        <div class=\"accordion-header d-flex align-items-center\" id=\"headingTwo\">\r\n");
      out.write("          <button class=\" btn collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#collapseTwo\"\r\n");
      out.write("            aria-expanded=\"false\" aria-controls=\"collapseOne\">\r\n");
      out.write("            <img src=\"images/down-arrow.png\" alt=\"\" height=\"22\" width=\"22\">\r\n");
      out.write("          </button>\r\n");
      out.write("          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nisl nunc, iaculis mattis tellus ac\r\n");
      out.write("            ut non imperdiet velit?</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"collapseTwo\" class=\"accordion-collapse collapse\" aria-labelledby=\"headingTwo\"\r\n");
      out.write("          data-bs-parent=\"#accordionServiceProvider\">\r\n");
      out.write("          <div class=\"accordion-body\">\r\n");
      out.write("            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed id diam tincidunt, fringilla ante vitae,\r\n");
      out.write("            dapibus velit. Vivamus id tortor rhoncus, efficitur quam at, suscipit tortor. Integer fermentum convallis\r\n");
      out.write("            eros vel semper. Ut non imperdiet velit. Praesent eu dui vel lacus porta eleifend eget quis dui. Integer\r\n");
      out.write("            tempus massa in gravida tincidunt. Fusce in libero tristique, euismod nisi vel, luctus urna. Interdum et\r\n");
      out.write("            malesuada fames ac ante ipsum primis in faucibus. Donec et placerat arcu. Suspendisse lacinia tristique\r\n");
      out.write("            massa. Etiam risus justo, scelerisque id arcu eu, sodales tempor eros. Aliquam efficitur pretium urna, sit\r\n");
      out.write("            amet congue risus malesuada rutrum. Donec id massa vel velit ullamcorper accumsan ut eget nisl. Fusce\r\n");
      out.write("            viverra commodo lacus, sit amet facilisis leo luctus dictum.\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"accordion-item border-0\">\r\n");
      out.write("        <div class=\"accordion-header d-flex align-items-center\" id=\"headingThree\">\r\n");
      out.write("          <button class=\" btn collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#collapseThree\"\r\n");
      out.write("            aria-expanded=\"false\" aria-controls=\"collapseThree\">\r\n");
      out.write("            <img src=\"images/down-arrow.png\" alt=\"\" height=\"22\" width=\"22\">\r\n");
      out.write("          </button>\r\n");
      out.write("          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nisl nunc, iaculis mattis tellus ac\r\n");
      out.write("            ut non imperdiet velit?</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"collapseThree\" class=\"accordion-collapse collapse\" aria-labelledby=\"headingThree\"\r\n");
      out.write("          data-bs-parent=\"#accordionServiceProvider\">\r\n");
      out.write("          <div class=\"accordion-body\">\r\n");
      out.write("            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed id diam tincidunt, fringilla ante vitae,\r\n");
      out.write("            dapibus velit. Vivamus id tortor rhoncus, efficitur quam at, suscipit tortor. Integer fermentum convallis\r\n");
      out.write("            eros vel semper. Ut non imperdiet velit. Praesent eu dui vel lacus porta eleifend eget quis dui. Integer\r\n");
      out.write("            tempus massa in gravida tincidunt. Fusce in libero tristique, euismod nisi vel, luctus urna. Interdum et\r\n");
      out.write("            malesuada fames ac ante ipsum primis in faucibus. Donec et placerat arcu. Suspendisse lacinia tristique\r\n");
      out.write("            massa. Etiam risus justo, scelerisque id arcu eu, sodales tempor eros. Aliquam efficitur pretium urna, sit\r\n");
      out.write("            amet congue risus malesuada rutrum. Donec id massa vel velit ullamcorper accumsan ut eget nisl. Fusce\r\n");
      out.write("            viverra commodo lacus, sit amet facilisis leo luctus dictum.\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"accordion-item border-0\">\r\n");
      out.write("        <div class=\"accordion-header d-flex align-items-center\" id=\"headingFour\">\r\n");
      out.write("          <button class=\" btn collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#collapseFour\"\r\n");
      out.write("            aria-expanded=\"false\" aria-controls=\"collapseThree\">\r\n");
      out.write("            <img src=\"images/down-arrow.png\" alt=\"\" height=\"22\" width=\"22\">\r\n");
      out.write("          </button>\r\n");
      out.write("          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nisl nunc, iaculis mattis tellus ac\r\n");
      out.write("            ut non imperdiet velit?</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"collapseFour\" class=\"accordion-collapse collapse\" aria-labelledby=\"headingFour\"\r\n");
      out.write("          data-bs-parent=\"#accordionServiceProvider\">\r\n");
      out.write("          <div class=\"accordion-body\">\r\n");
      out.write("            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed id diam tincidunt, fringilla ante vitae,\r\n");
      out.write("            dapibus velit. Vivamus id tortor rhoncus, efficitur quam at, suscipit tortor. Integer fermentum convallis\r\n");
      out.write("            eros vel semper. Ut non imperdiet velit. Praesent eu dui vel lacus porta eleifend eget quis dui. Integer\r\n");
      out.write("            tempus massa in gravida tincidunt. Fusce in libero tristique, euismod nisi vel, luctus urna. Interdum et\r\n");
      out.write("            malesuada fames ac ante ipsum primis in faucibus. Donec et placerat arcu. Suspendisse lacinia tristique\r\n");
      out.write("            massa. Etiam risus justo, scelerisque id arcu eu, sodales tempor eros. Aliquam efficitur pretium urna, sit\r\n");
      out.write("            amet congue risus malesuada rutrum. Donec id massa vel velit ullamcorper accumsan ut eget nisl. Fusce\r\n");
      out.write("            viverra commodo lacus, sit amet facilisis leo luctus dictum.\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"accordion-item border-0\">\r\n");
      out.write("        <div class=\"accordion-header d-flex align-items-center\" id=\"headingFive\">\r\n");
      out.write("          <button class=\" btn collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#collapseFive\"\r\n");
      out.write("            aria-expanded=\"false\" aria-controls=\"collapseThree\">\r\n");
      out.write("            <img src=\"images/down-arrow.png\" alt=\"\" height=\"22\" width=\"22\">\r\n");
      out.write("          </button>\r\n");
      out.write("          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nisl nunc, iaculis mattis tellus ac\r\n");
      out.write("            ut non imperdiet velit?</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"collapseFive\" class=\"accordion-collapse collapse\" aria-labelledby=\"headingFive\"\r\n");
      out.write("          data-bs-parent=\"#accordionServiceProvider\">\r\n");
      out.write("          <div class=\"accordion-body\">\r\n");
      out.write("            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed id diam tincidunt, fringilla ante vitae,\r\n");
      out.write("            dapibus velit. Vivamus id tortor rhoncus, efficitur quam at, suscipit tortor. Integer fermentum convallis\r\n");
      out.write("            eros vel semper. Ut non imperdiet velit. Praesent eu dui vel lacus porta eleifend eget quis dui. Integer\r\n");
      out.write("            tempus massa in gravida tincidunt. Fusce in libero tristique, euismod nisi vel, luctus urna. Interdum et\r\n");
      out.write("            malesuada fames ac ante ipsum primis in faucibus. Donec et placerat arcu. Suspendisse lacinia tristique\r\n");
      out.write("            massa. Etiam risus justo, scelerisque id arcu eu, sodales tempor eros. Aliquam efficitur pretium urna, sit\r\n");
      out.write("            amet congue risus malesuada rutrum. Donec id massa vel velit ullamcorper accumsan ut eget nisl. Fusce\r\n");
      out.write("            viverra commodo lacus, sit amet facilisis leo luctus dictum.\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"accordion-item border-0\">\r\n");
      out.write("        <div class=\"accordion-header d-flex align-items-center\" id=\"headingSix\">\r\n");
      out.write("          <button class=\" btn collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#collapseSix\"\r\n");
      out.write("            aria-expanded=\"false\" aria-controls=\"collapseThree\">\r\n");
      out.write("            <img src=\"images/down-arrow.png\" alt=\"\" height=\"22\" width=\"22\">\r\n");
      out.write("          </button>\r\n");
      out.write("          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nisl nunc, iaculis mattis tellus ac\r\n");
      out.write("            ut non imperdiet velit?</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"collapseSix\" class=\"accordion-collapse collapse\" aria-labelledby=\"headingSix\"\r\n");
      out.write("          data-bs-parent=\"#accordionServiceProvider\">\r\n");
      out.write("          <div class=\"accordion-body\">\r\n");
      out.write("            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed id diam tincidunt, fringilla ante vitae,\r\n");
      out.write("            dapibus velit. Vivamus id tortor rhoncus, efficitur quam at, suscipit tortor. Integer fermentum convallis\r\n");
      out.write("            eros vel semper. Ut non imperdiet velit. Praesent eu dui vel lacus porta eleifend eget quis dui. Integer\r\n");
      out.write("            tempus massa in gravida tincidunt. Fusce in libero tristique, euismod nisi vel, luctus urna. Interdum et\r\n");
      out.write("            malesuada fames ac ante ipsum primis in faucibus. Donec et placerat arcu. Suspendisse lacinia tristique\r\n");
      out.write("            massa. Etiam risus justo, scelerisque id arcu eu, sodales tempor eros. Aliquam efficitur pretium urna, sit\r\n");
      out.write("            amet congue risus malesuada rutrum. Donec id massa vel velit ullamcorper accumsan ut eget nisl. Fusce\r\n");
      out.write("            viverra commodo lacus, sit amet facilisis leo luctus dictum.\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"accordion-item border-0\">\r\n");
      out.write("        <div class=\"accordion-header d-flex align-items-center\" id=\"headingSeven\">\r\n");
      out.write("          <button class=\" btn collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#collapseSeven\"\r\n");
      out.write("            aria-expanded=\"false\" aria-controls=\"collapseThree\">\r\n");
      out.write("            <img src=\"images/down-arrow.png\" alt=\"\" height=\"22\" width=\"22\">\r\n");
      out.write("          </button>\r\n");
      out.write("          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nisl nunc, iaculis mattis tellus ac\r\n");
      out.write("            ut non imperdiet velit?</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"collapseSeven\" class=\"accordion-collapse collapse\" aria-labelledby=\"headingSeven\"\r\n");
      out.write("          data-bs-parent=\"#accordionServiceProvider\">\r\n");
      out.write("          <div class=\"accordion-body\">\r\n");
      out.write("            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed id diam tincidunt, fringilla ante vitae,\r\n");
      out.write("            dapibus velit. Vivamus id tortor rhoncus, efficitur quam at, suscipit tortor. Integer fermentum convallis\r\n");
      out.write("            eros vel semper. Ut non imperdiet velit. Praesent eu dui vel lacus porta eleifend eget quis dui. Integer\r\n");
      out.write("            tempus massa in gravida tincidunt. Fusce in libero tristique, euismod nisi vel, luctus urna. Interdum et\r\n");
      out.write("            malesuada fames ac ante ipsum primis in faucibus. Donec et placerat arcu. Suspendisse lacinia tristique\r\n");
      out.write("            massa. Etiam risus justo, scelerisque id arcu eu, sodales tempor eros. Aliquam efficitur pretium urna, sit\r\n");
      out.write("            amet congue risus malesuada rutrum. Donec id massa vel velit ullamcorper accumsan ut eget nisl. Fusce\r\n");
      out.write("            viverra commodo lacus, sit amet facilisis leo luctus dictum.\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"accordion-item border-0\">\r\n");
      out.write("        <div class=\"accordion-header d-flex align-items-center\" id=\"headingEight\">\r\n");
      out.write("          <button class=\" btn collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#collapseEight\"\r\n");
      out.write("            aria-expanded=\"false\" aria-controls=\"collapseThree\">\r\n");
      out.write("            <img src=\"images/down-arrow.png\" alt=\"\" height=\"22\" width=\"22\">\r\n");
      out.write("          </button>\r\n");
      out.write("          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nisl nunc, iaculis mattis tellus ac\r\n");
      out.write("            ut non imperdiet velit?</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"collapseEight\" class=\"accordion-collapse collapse\" aria-labelledby=\"headingEight\"\r\n");
      out.write("          data-bs-parent=\"#accordionServiceProvider\">\r\n");
      out.write("          <div class=\"accordion-body\">\r\n");
      out.write("            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed id diam tincidunt, fringilla ante vitae,\r\n");
      out.write("            dapibus velit. Vivamus id tortor rhoncus, efficitur quam at, suscipit tortor. Integer fermentum convallis\r\n");
      out.write("            eros vel semper. Ut non imperdiet velit. Praesent eu dui vel lacus porta eleifend eget quis dui. Integer\r\n");
      out.write("            tempus massa in gravida tincidunt. Fusce in libero tristique, euismod nisi vel, luctus urna. Interdum et\r\n");
      out.write("            malesuada fames ac ante ipsum primis in faucibus. Donec et placerat arcu. Suspendisse lacinia tristique\r\n");
      out.write("            massa. Etiam risus justo, scelerisque id arcu eu, sodales tempor eros. Aliquam efficitur pretium urna, sit\r\n");
      out.write("            amet congue risus malesuada rutrum. Donec id massa vel velit ullamcorper accumsan ut eget nisl. Fusce\r\n");
      out.write("            viverra commodo lacus, sit amet facilisis leo luctus dictum.\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"accordion-item border-0\">\r\n");
      out.write("        <div class=\"accordion-header d-flex align-items-center\" id=\"headingNine\">\r\n");
      out.write("          <button class=\" btn collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#collapseNine\"\r\n");
      out.write("            aria-expanded=\"false\" aria-controls=\"collapseThree\">\r\n");
      out.write("            <img src=\"images/down-arrow.png\" alt=\"\" height=\"22\" width=\"22\">\r\n");
      out.write("          </button>\r\n");
      out.write("          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nisl nunc, iaculis mattis tellus ac\r\n");
      out.write("            ut non imperdiet velit?</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"collapseNine\" class=\"accordion-collapse collapse\" aria-labelledby=\"headingNine\"\r\n");
      out.write("          data-bs-parent=\"#accordionServiceProvider\">\r\n");
      out.write("          <div class=\"accordion-body\">\r\n");
      out.write("            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed id diam tincidunt, fringilla ante vitae,\r\n");
      out.write("            dapibus velit. Vivamus id tortor rhoncus, efficitur quam at, suscipit tortor. Integer fermentum convallis\r\n");
      out.write("            eros vel semper. Ut non imperdiet velit. Praesent eu dui vel lacus porta eleifend eget quis dui. Integer\r\n");
      out.write("            tempus massa in gravida tincidunt. Fusce in libero tristique, euismod nisi vel, luctus urna. Interdum et\r\n");
      out.write("            malesuada fames ac ante ipsum primis in faucibus. Donec et placerat arcu. Suspendisse lacinia tristique\r\n");
      out.write("            massa. Etiam risus justo, scelerisque id arcu eu, sodales tempor eros. Aliquam efficitur pretium urna, sit\r\n");
      out.write("            amet congue risus malesuada rutrum. Donec id massa vel velit ullamcorper accumsan ut eget nisl. Fusce\r\n");
      out.write("            viverra commodo lacus, sit amet facilisis leo luctus dictum.\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <div class=\"email_form d-flex align-items-center justify-content-center w-100\">\r\n");
      out.write("    <div class=\"email_mid d-flex flex-column align-items-center justify-content-center\">\r\n");
      out.write("      <h5 class=\"email_heading\">GET OUR NEWSLETTER </h5>\r\n");
      out.write("      <form action=\"\">\r\n");
      out.write("        <input type=\"email\" placeholder=\"YOUR EMAIL\" class=\"email_input rounded-pill\">\r\n");
      out.write("        <button type=\"submit\" class=\"btn email_btn rounded-pill text-light\">Submit</button>\r\n");
      out.write("      </form>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"footer_section w-100\">\r\n");
      out.write("    <div class=\"footer_main d-flex justify-content-center align-items-center position-relative\">\r\n");
      out.write("      <div class=\"d-flex justify-content-between h-100 align-items-center footer_inner position-relative\">\r\n");
      out.write("        <div class=\"footer_left\">\r\n");
      out.write("          <img src=\"images/logo-small.png\" alt=\"\" height=\"78\" width=\"106\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"footer_mid\">\r\n");
      out.write("          <ul class=\"d-flex p-0 text-center m-0\">\r\n");
      out.write("            <li>\r\n");
      out.write("              <a href=\"homepage.html\" class=\"text-decoration-none\">HOME</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("              <a href=\"about.html\" class=\"text-decoration-none\">ABOUT</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("              <a href=\"\" class=\"text-decoration-none\">TESTIMONIAL</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("              <a href=\"faq.html\" class=\"text-decoration-none\">FAQS</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("              <a href=\"\" class=\"text-decoration-none\">INSURANCE POLICY</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("              <a href=\"\" class=\"text-decoration-none\">IMPRESSUM</a>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"footer_right d-flex align-items-center justify-content-evenly\">\r\n");
      out.write("          <img src=\"images/ic-facebook.png\" width=\"9\" height=\"18\">\r\n");
      out.write("\r\n");
      out.write("          <img src=\"images/ic-instagram.png\" width=\"20\" height=\"20\">\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"footer_end d-flex align-items-center justify-content-center position-relative\">\r\n");
      out.write("      <p class=\"m-0 text-center\">©2018 Helperland. All rights reserved. &nbsp;&nbsp;<span><a href=\"\"\r\n");
      out.write("            class=\"text-decoration-none\">Terms and Conditions</a></span> | <span><a href=\"\"\r\n");
      out.write("            class=\"text-decoration-none\">Privacy Policy</a></span></p>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("    integrity=\"sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p\"\r\n");
      out.write("    crossorigin=\"anonymous\"></script>\r\n");
      out.write(" \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/views/faq.jsp(11,32) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/resources/css/faq.css");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }
}
