/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.47
 * Generated at: 2022-02-07 06:50:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/E:/HelperLand/helperland/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/helperland/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1643955185828L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\" />\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("    <title>register</title>\r\n");
      out.write("    \r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("  \r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\"\r\n");
      out.write("        integrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\" crossorigin=\"anonymous\" />\r\n");
      out.write("  \r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"\r\n");
      out.write("        integrity=\"sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=\" crossorigin=\"anonymous\">\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <div style=\"min-height: 100vh; padding-bottom: 150px;\">\r\n");
      out.write("        <nav class=\"navbar navbar-expand-xl\" id=\"navbar\">\r\n");
      out.write("            <div class=\"container-fluid navbar_main\">\r\n");
      out.write("              <a class=\"navbar-brand py-0\" href=\"homepage.html\">\r\n");
      out.write("                <img src=\"images/logo-small.png\" alt=\"\" height=\"54px\" width=\"73px\">\r\n");
      out.write("              </a>\r\n");
      out.write("              <button class=\"navbar-toggler text-white\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarText\"\r\n");
      out.write("                aria-controls=\"navbarText\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("                <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"40\" height=\"40\" fill=\"#fff\" class=\"bi bi-list\"\r\n");
      out.write("                  viewBox=\"0 0 16 16\">\r\n");
      out.write("                  <path fill-rule=\"evenodd\"\r\n");
      out.write("                    d=\"M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z\" />\r\n");
      out.write("                </svg>\r\n");
      out.write("              </button>\r\n");
      out.write("              <div class=\"collapse navbar-collapse navbar_list\" id=\"navbarText\">\r\n");
      out.write("                <div class=\"nav-item navbar_book rounded-pill\">\r\n");
      out.write("                  <a class=\"p-0 nav-link text-light\" href=\"#\">Book now</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"nav-item navbar_prices rounded-pill\">\r\n");
      out.write("                  <a class=\"p-0 nav-link text-light\" href=\"prices.html\">Prices & services</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <ul class=\"navbar-nav me-auto mb-2 mb-lg-0 align-items-center justify-content-between\">\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link text-light\" href=\"#\">Warranty</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link text-light\" href=\"#\">Blog</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"nav-item navbar_contact\">\r\n");
      out.write("                    <a class=\"nav-link text-light\" href=\"contact\">Contact</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <div class=\"nav-item navbar_login rounded-pill\">\r\n");
      out.write("                  <a href=\"homepage\" class=\"p-0 text-decoration-none text-light\">Login</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"nav-item navbar_helper rounded-pill\">\r\n");
      out.write("                  <a href=\"becomeApro.html\" class=\"p-0 text-decoration-none text-light\">Become a Helper</a>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </nav>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"userReg_heading position-relative mt-5\">\r\n");
      out.write("            <h1>Create An Account</h1>\r\n");
      out.write("            <div class=\"userReg_box\">\r\n");
      out.write("             \r\n");
      out.write("                <img src=\"images/separator.png\" alt=\"\" />\r\n");
      out.write("               \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"userRegForm_wrapper my-5\">\r\n");
      out.write("            <form action=\"create_user\" class=\"userRegForm\" method=\"post\">\r\n");
      out.write("                <input type=\"hidden\" id=\"userType\" name=\"userType\" value=\"customer\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-sm-6 mb-4\">\r\n");
      out.write("                        <div class=\"form-group d-flex flex-column\">\r\n");
      out.write("                            <input type=\"text\" required name=\"FirstName\" placeholder=\"First name\" class=\"inputHeightBorderPadding form-control\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-sm-6 mb-4\">\r\n");
      out.write("                        <div class=\"form-group d-flex flex-column\">\r\n");
      out.write("                            <input type=\"text\" required name=\"LastName\" id=\"lastname\" placeholder=\"Last name\" class=\"inputHeightBorderPadding form-control\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-sm-6 mb-4\">\r\n");
      out.write("                        <div class=\"form-group d-flex flex-column\">\r\n");
      out.write("                            <input type=\"email\" required name=\"Email\" id=\"emailaddress\" placeholder=\"Email Address\" class=\"inputHeightBorderPadding form-control\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-sm-6 mb-4\">\r\n");
      out.write("                        <div class=\"form-group d-flex flex-column\">\r\n");
      out.write("                            <div class=\"d-flex\">\r\n");
      out.write("                                <input type=\"text\" value=\"+49\" disabled style=\"max-width: 55px;\" class=\"inputHeightBorderPadding form-control\">\r\n");
      out.write("                                <input type=\"text\" name=\"Mobile\" id=\"mobilenumber\" placeholder=\"Mobile number\" class=\"inputHeightBorderPadding form-control\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <small id=\"mobileNumberMessage\"></small>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-sm-6 mb-4\">\r\n");
      out.write("                        <div class=\"form-group d-flex flex-column\">\r\n");
      out.write("                            <input type=\"password\" required name=\"Password\" title=\"Password must include uppercase letter , lowercase letter , number , special character and length should be more than 8\" pattern=\"(?=.*\\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[/\\w/]).{8,}\" id=\"password\" placeholder=\"Password\" class=\"inputHeightBorderPadding form-control\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-sm-6 mb-4\">\r\n");
      out.write("                        <div class=\"form-group d-flex flex-column\">\r\n");
      out.write("                            <input type=\"password\" required name=\"confirmpassword\"  id=\"confirmpassword\" placeholder=\"Confirm password\" class=\"inputHeightBorderPadding form-control\">\r\n");
      out.write("                            <small id=\"confirmPasswordMessage\"></small>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"d-flex align-items-center my-2\">\r\n");
      out.write("                    <input type=\"checkbox\" name=\"termsandconditions\" required>\r\n");
      out.write("                    <label for=\"termsandconditions\" class=\"fs14 ms-3\">I agree with the <span><a href=\"#\" class=\"text-decoration-none colorGreen\">terms and conditions</a></span> of Helperland GmbH.</label>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"d-flex align-items-center my-2\">\r\n");
      out.write("                    <input type=\"checkbox\" name=\"privacypolicy\" required>\r\n");
      out.write("                    <label for=\"privacypolicy\" class=\"fs14 ms-3\">I have read the <span><a href=\"#\" class=\"text-decoration-none colorGreen\">privacy policy.</a></span> </label>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"text-center mt-4\"> \r\n");
      out.write("                    <button class=\"btn submitButton text-light rounded-pill\"  type=\"submit\" id=\"registerButton\">Register</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("            <div class=\"text-center mt-3 color646464\">\r\n");
      out.write("                Already registered? \r\n");
      out.write("                <span><a class=\"colorGreen text-decoration-none\" href=\"homepage.html\">Login now</a></span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"footer_section w-100\" style=\"margin-top: -150px;\">\r\n");
      out.write("        <div class=\"footer_main d-flex justify-content-center align-items-center position-relative\">\r\n");
      out.write("            <div class=\"d-flex justify-content-between h-100 align-items-center footer_inner position-relative\">\r\n");
      out.write("                <div class=\"footer_left\">\r\n");
      out.write("                    <a href=\"homepage.html\">\r\n");
      out.write("                        <img src=\"images/logo-small.png\" alt=\"\" height=\"78\" width=\"106\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"footer_mid\">\r\n");
      out.write("                    <ul class=\"d-flex p-0 text-center m-0\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"homepage\" class=\"text-decoration-none\">HOME</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"about\" class=\"text-decoration-none\">ABOUT</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\" class=\"text-decoration-none\">TESTIMONIAL</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"faq\" class=\"text-decoration-none\">FAQS</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"\" class=\"text-decoration-none\">INSURANCE POLICY</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"\" class=\"text-decoration-none\">IMPRESSUM</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"footer_right d-flex align-items-center justify-content-evenly\">\r\n");
      out.write("                    <a href=\"https://www.facebook.com/TatvaSoft/\" target=\"_blank\">\r\n");
      out.write("                        <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"9\" height=\"18\">\r\n");
      out.write("                            <path fill-rule=\"evenodd\" fill=\"#CCC\" d=\"M1.947 3.48v2.481H0v3.033h1.947V18.1h4.001V8.995h2.685S8.885 7.541 9.7 5.95H5.963V3.876c0-.31.437-.728.868-.728H9.11V.9H6.46C1.848.9 1.947 3.27 1.947 3.48z\"/>\r\n");
      out.write("                        </svg>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"https://www.instagram.com/\" target=\"_blank\">\r\n");
      out.write("                        <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\">\r\n");
      out.write("                            <path fill-rule=\"evenodd\" fill=\"#CCC\" d=\"M14.48 20H5.519A5.524 5.524 0 0 1 0 14.482V5.52C0 2.477 2.475.2 5.519.2h8.961c3.043 0 5.519 2.277 5.519 5.32v8.962A5.525 5.525 0 0 1 14.48 20zm3.744-5.518V5.52a3.748 3.748 0 0 0-3.744-3.744H5.519A3.749 3.749 0 0 0 1.774 5.52v8.962a3.749 3.749 0 0 0 3.745 3.744h8.961a3.748 3.748 0 0 0 3.744-3.744zm-2.855-8.536c-.099 0-.678-.14-.92-.381-.242-.243.221-.578.221-.921 0-.342-.463-.678-.221-.92.242-.242.821-.381.92-.381.343 0 1.111.139.92.381.242.242.381.578.381.92 0 .342-.139.678-.381.921.171.241-.577.381-.92.381zm-5.37 9.208c-2.841 0-5.153-2.312-5.153-5.054 0-2.941 2.312-5.252 5.153-5.252 2.842 0 5.153 2.311 5.153 5.252 0 2.742-2.311 5.054-5.153 5.054zm0-8.532c-1.863 0-3.379 1.516-3.379 3.478 0 1.764 1.516 3.28 3.379 3.28s3.379-1.516 3.379-3.28c0-1.962-1.516-3.478-3.379-3.478z\"/>\r\n");
      out.write("                        </svg>   \r\n");
      out.write("                    </a>                                     \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"footer_end d-flex align-items-center justify-content-center position-relative \">\r\n");
      out.write("            <p class=\"m-0 text-center\">©2018 Helperland. All rights reserved. &nbsp;&nbsp;<span><a href=\"\" class=\"text-decoration-none\">Terms and Conditions</a></span> | <span><a href=\"\" class=\"text-decoration-none\">Privacy Policy</a></span></p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("    integrity=\"sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p\"\r\n");
      out.write("    crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/views/register.jsp(13,33) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/resources/css/register.css");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }
}
